### ISSUE TITLE
Multi language use

### ISSUE THREAD

**Issue by maggie44** [strapi/strapi-starter-next-corporate#17]
Thanks for this corporate starter example, it’s a really helpful way to get insight into Strapi’s functionality. 

Where I’m left a little hesitant is in incorporating multi-language support (a common function in corporate as elsewhere I’m sure). One would usually utilise JSON file systems allowing all the strings for each language to be kept tidily together and allow crowdin or weblate integration. What would the workflow look like in this Strapi-next-corporate scenario?

**Comment by remidej** [comment]
Hello!

The core Strapi team is working on [content internationalization](https://portal.productboard.com/strapi/1-roadmap/c/19-content-internationalization-ce-ee-v4). Once it's live, we will update our starters to use this new feature.

In the meantime, one way you could do this is by adding a suffix to your fields. For example, instead of `title`, have a `title_en` and a `title_es` field

**Comment by maggie44** [comment]
This is extremely helpful, and promising. Will up vote the feature on the page you referred to, thanks for the info.
