### ISSUE TITLE
Seeding data for development

### ISSUE THREAD

**Issue by mdwt** [strapi/strapi-starter-next-corporate#3]
Hi there,

The seed script seems to be missing from the back package, the `back/README.md` states to run `yarn seed` but there's no such script.

I notice there is a data dump in the project root, can that be imported to SQLite?

**Comment by remidej** [comment]
Hello! Thanks for the early feedback.

The seed script doesn't exist anymore, that part of the docs should have been removed. Also, the data dump in the project root is a Postgres dump, so no, you cannot import it to SQLite.

We realize this a major pain point to test the starter in development. That's why we'll change the docs to recommend running Postgres in production. This way, you can import the `data.dump` at the root of the project.

In the meantime, you can follow [the instructions provided here](https://github.com/strapi/strapi-starter-next-corporate/issues/4#issuecomment-667640033) to get started with this starter using Postgres.

**Comment by mdwt** [comment]
Ok thanks for clearing that up.

I followed those instructions you linked and got it up and running.
